version: '3.8'
services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j-data:/data
  backend:
    build: ./backend
    container_name: family-tree-backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - JWT_SECRET=supersecret
    depends_on:
      - neo4j
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    container_name: family-tree-frontend
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  neo4j-data:
